# Generated by Django 5.1 on 2025-04-29 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_questionsspecifiques_service_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontransversale',
            name='question_specifique',
        ),
    ]
