# Generated by Django 5.1 on 2025-05-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_questiontransversale_question_specifique'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontransversale',
            name='statut',
            field=models.BooleanField(default=0),
        ),
    ]
